### ISSUE TITLE
Retrieving a request_token from Twitter fails with Requests-oauth 0.2.2 and Requests 0.8.1


### ISSUE THREAD

**Issue by ctoth** [maraujop/requests-oauth#6] opened 2011-11-19 11:23 UTC
Previously, posting to https://api.twitter.com/oauth/request_token with a consumer key and secret provided would give back a useable request token. It now gives a rather useless http 401 error:

``` python
>>> r=t.client.post('https://api.twitter.com/oauth/request_token')
>>> r
<Response [401]>
>>> r.content
u'Failed to validate oauth signature and token'
>>> r.request.headers
{'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'identi
ty, deflate, compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/0.
8.1'}
>>> r.request.params
{'oauth_nonce': '69262010', 'oauth_timestamp': '1321701553', 'oauth_consumer_key
': 'Iay3HXuKW3lYQ1REEKnWg', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_versio
n': '1.0', 'oauth_signature': 'wcPIt0x1G0MpE+eO9NNQUwruRP8='}
>>> r.request.data
{}
>>> r.request.cookies
{'guest_id': 'v1%3A132170155381775185', '_twitter_sess': 'BAh7CDoPY3JlYXRlZF9hdG
wrCJo2jbszAToHaWQiJTU5MWVjNmJjYjRiZTA1%250AMmRhM2UxMDZlNWM4Yjk2MWE1IgpmbGFzaElDO
idBY3Rpb25Db250cm9sbGVy%250AOjpGbGFzaDo6Rmxhc2hIYXNoewAGOgpAdXNlZHsA--1ba7fb8449
bec52a105b50b825a4623c35a2fe07', 'k': '10.35.56.136.1321701553810853'}
>>>
```

**Comment by maraujop** [comment] 2011-11-20 11:09
Christopher I have a test in `tests/tests.py` named `test_twitter_oauth_get_token` that requests this URL and it's passing with version 0.2.2 of requests-oauth and latest requests library.

Please make sure you are using latest version of `requests-oauth` (beware of the name change I did some time ago, it's not requests-oauth-hook anymore). If you are using the right version, I will need you to post some extra code, because I cannot reproduce the bug.

Cheers,
Miguel

**Comment by ctoth** [comment] 2011-11-20 20:16
I cloned the latest requests-oauth into a new directory. Filled in 
test_settings.py (btw, you need to change the settings in there, as it 
requires a TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET, and the 
unset settings are for TWITTER_ACCESS_TOKEN and stuff.
I ran discover, and got the following:
C:\Users\Q\others\requests-oauth>discover

# EEE.F.F

## ERROR: test_rdio_oauth_get_token_data (tests.tests.OAuthTestSuite)

Traceback (most recent call last):
   File "C:\Users\Q\others\requests-oauth\tests\tests.py", line 63, in 
test_rdio_
oauth_get_token_data
     self.assertTrue(response['oauth_token'])
KeyError: 'oauth_token'

# 

## ERROR: test_rdio_oauth_get_token_params (tests.tests.OAuthTestSuite)

Traceback (most recent call last):
   File "C:\Users\Q\others\requests-oauth\tests\tests.py", line 70, in 
test_rdio_
oauth_get_token_params
     self.assertTrue(response['oauth_token'])
KeyError: 'oauth_token'

# 

ERROR: test_twitter_delete (tests.tests.OAuthTestSuite)
Depends on GET and POST also working properly, as we must first 
determine the cu

## rrent username and then create a test list to subsequently delete.

Traceback (most recent call last):
   File "C:\Users\Q\others\requests-oauth\tests\tests.py", line 44, in 
test_twitt
er_delete
     screen_name = 
json.loads(client.get('https://api.twitter.com/1/account/verif
y_credentials.json').content)['screen_name']
KeyError: 'screen_name'

# 

## FAIL: test_twitter_rate_limit_GET (tests.tests.OAuthTestSuite)

Traceback (most recent call last):
   File "C:\Users\Q\others\requests-oauth\tests\tests.py", line 28, in 
test_twitt
er_rate_limit_GET
     self.assertEqual(json.loads(response.content)['hourly_limit'], 350)
AssertionError: 150 != 350

# 

## FAIL: test_twitter_status_POST (tests.tests.OAuthTestSuite)

Traceback (most recent call last):
   File "C:\Users\Q\others\requests-oauth\tests\tests.py", line 34, in 
test_twitt
er_status_POST
     self.assertEqual(response.status_code, 200)
AssertionError: 401 != 200

---

Ran 7 tests in 3.205s

FAILED (failures=2, errors=3)

C:\Users\Q\others\requests-oauth>
Not sure if I'm not doing something right, but this is with latest 
Requests, now 0.8.2, and latest requests-oauth from Github.

**Comment by maraujop** [comment] 2011-11-25 11:21
Christopher can we please talk about this issue publicly?

You've told me you've got all tests running excepting the request token one. What did you do to make them work?

Have you tried for example requests-oauth 0.2.3 with requests 0.7 to see if it works?

This might be related to the fact that you are using a Windows box? I don't have a way to reproduce the problems you have, all tests run right in my Linux box.

Cheers,
Miguel

**Comment by ctoth** [comment] 2011-11-25 12:39
For the tests, I expected the test to retrieve the access token. It did 
not, once I plugged in one it worked fine.
0.2.1 is the last version of requests-oauth that works with the 0.7.x 
series of requests. With 0.2.2 there's some issue regarding cookie 
support -- I think requests 0.8 stops using a dict for cookies or 
something. and 0.2.2 expects this and won't work with older versions.
I'm getting variable-length postdata requests, ranging from 298 
(failing) 299-301 (succeeding)
These are requests to access_token once I have an oauth_verifier.

**Comment by maraujop** [comment] 2011-11-25 13:59
There are several things you could try to debug this:
- Add a verbose flag to requests-oauth that prints several parameters from the request, to compare what differs from one version to other. Things like `request.params`, `request.headers`, `request.cookies`, `request.url` etc.
- Maybe you could post the different postdata results, not only the lengths, so I can inspect them to see if I find a difference.
- Try to run the test that fails alone, only that single test, to make sure other tests don't have side effects on it.

Remember that this could be an issue related to requests-oauth or to requests itself. Thanks for trying this hard on fixing the issue.

Cheers,
Miguel

**Comment by maraujop** [comment] 2011-12-22 10:14
Any progress on this?

Future version of requests-oauth is now in `dev` branch. You can try it out if you want, to see if it fixes your issue.

**Comment by maraujop** [comment] 2012-01-13 18:01
I've just release version 0.3.0 of requests-oauth

Could you please try to see if you can reproduce this bug? 

If I don't get an answer, i will be closing the issue, sorry.

**Closed as completed** 2012-01-17 11:05 UTC
